version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=authdb
    depends_on:
      - postgres
   

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
